### ISSUE TITLE
Avg reports malicious apk

### ISSUE THREAD

**Issue by Bazmundi** [Gemesys/gemesys_repository#1]
Both watapl and gkeyboard.

**Comment by Gemesys** [comment]
Hello Asterion;

Not sure why Avg would report malicious apk.
WatAPL uses gDOSbox, and it has a .COM file
embedded within it: WRUN.COM.

It also has an associated utility program called
"trancopy.exe" which lets files be translated
between DOS and Linux format (CR/LF line
ends versus LF line ends).

AvG might be seeing an .exe and a .COM file
in WatAPL and flagging these as unsafe.

Not sure why Gkeyboard would be flagged.

If you have a Linux box, running "gpg", you
can check the "message digest" (the hash
value) for each of the GEMESYS APK files.
These should match the info on this panel on
our website mainpage (near the bottom):
(direct link to .jpg file, URL below)

http://cdn.simplesite.com/i/42/40/285134156850413634/i285134164458076887._szw1280h1280_.jpg

I've also attached a .JPG file to this note. If
you have "gpg", run this command:

gpg  --print-md sha256  <APK-filename>

 against any of the GEMESYS
.APK files, to show their SHA256 hash.  To the best
of my knowledge, the .APKs on Github are free
of viruses or any malicious code.  If anyone
has injected malicious code into any of the APKs,
then the SHA256 hash calculations will be
different.

Hope this helps.  Note also that our .APKs
are completely free from advertizing or any
tracking software.  I made them because I
personally wanted to use them on my Android
devices, and I wanted modern folks to have
some ability to access the code-bases of
fine APL applications.   We also built
versions for the Apple iPad, but Apple will
not allow any programming language tools
that run native on the machine, to be offered
in their iTunes store.

Google removed our APK's from their
Playstore, because they are not current to the
latest Android version.

It became clear to us, that the Android
version-churn and it's API-churn, is just
a methodology being used by Google to
ensure their competitive dominance.

Since we derive no revenue from these
.APKs, we offer them on GitHub for
download by researchers and APL
experimenters for educational and/or
any commerical use they wish to make
of them.   Hope this information is useful!

Cheers!

M. Langdon, Director/Owner, Gemesys Ltd.
